In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv("dataset.csv")
dataset

Index region online shopper   age   salary
0       0    ind            yes  25.0  35000.0
1       1    bra             no  27.0  40000.0
2       2    usa            yes  50.0  54000.0
3       3    bra            yes  35.0      NaN
4       4   ind              no  40.0  60000.0
5       5    usa             no  35.0  58000.0
6       6    bra            yes   NaN  52000.0
7       7    ind             no  48.0  79000.0
8       8    usa            yes  50.0  83000.0
9       9    ind             no  37.0      NaN
10     10    bra            yes  21.0  24000.0
11     11    ind            yes   NaN  60000.0
12     12    usa             no  63.0  70000.0

In [3]:
x = dataset.iloc[:,[0,2,3]].values

x

array([[0, 'yes', 25.0],
       [1, 'no', 27.0],
       [2, 'yes', 50.0],
       [3, 'yes', 35.0],
       [4, 'no', 40.0],
       [5, 'no', 35.0],
       [6, 'yes', nan],
       [7, 'no', 48.0],
       [8, 'yes', 50.0],
       [9, 'no', 37.0],
       [10, 'yes', 21.0],
       [11, 'yes', nan],
       [12, 'no', 63.0]], dtype=object)

In [4]:
y = dataset.iloc[:,1].values

y

array(['ind', 'bra', 'usa', 'bra', 'ind ', 'usa', 'bra', 'ind', 'usa',
       'ind', 'bra', 'ind', 'usa'], dtype=object)

In [5]:
ct = ColumnTransformer([("country",OneHotEncoder(),[1])],remainder='passthrough')

x = ct.fit_transform(x)
x

array([[0.0, 1.0, 0, 25.0],
       [1.0, 0.0, 1, 27.0],
       [0.0, 1.0, 2, 50.0],
       [0.0, 1.0, 3, 35.0],
       [1.0, 0.0, 4, 40.0],
       [1.0, 0.0, 5, 35.0],
       [0.0, 1.0, 6, nan],
       [1.0, 0.0, 7, 48.0],
       [0.0, 1.0, 8, 50.0],
       [1.0, 0.0, 9, 37.0],
       [0.0, 1.0, 10, 21.0],
       [0.0, 1.0, 11, nan],
       [1.0, 0.0, 12, 63.0]], dtype=object)

In [6]:
LabelEncoder_x = LabelEncoder()

x[:,2] = LabelEncoder_x.fit_transform(x[:,2])

x

array([[0.0, 1.0, 0, 25.0],
       [1.0, 0.0, 1, 27.0],
       [0.0, 1.0, 2, 50.0],
       [0.0, 1.0, 3, 35.0],
       [1.0, 0.0, 4, 40.0],
       [1.0, 0.0, 5, 35.0],
       [0.0, 1.0, 6, nan],
       [1.0, 0.0, 7, 48.0],
       [0.0, 1.0, 8, 50.0],
       [1.0, 0.0, 9, 37.0],
       [0.0, 1.0, 10, 21.0],
       [0.0, 1.0, 11, nan],
       [1.0, 0.0, 12, 63.0]], dtype=object)

In [7]:
X_train,X_test,Y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [8]:
sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)

X_test = sc_X.transform(X_test)

sc_y = StandardScaler()

#Y_train = Y_train.reshape((len(Y_train), 1))

#Y_train = sc_y.fit_transform(Y_train)

Y_train = Y_train.ravel()

In [9]:
Y_train

array(['usa', 'usa', 'bra', 'ind', 'ind', 'bra', 'ind', 'usa', 'usa'],
      dtype=object)